spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/notifications`}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/notifications`}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:`localhost:29092`}
    producer:
      acks: all

# Custom
kafka:
  topics:
    email-notifications:
      name: email-notifications
      partitions: 5
    sms-notifications:
      name: sms-notifications
      partitions: 5
    slack-notifications:
      name: slack-notifications
      partitions: 5