spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notifications
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/notifications
    user: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      acks: all
      properties:
        enable.idempotence: true

# Custom
kafka:
  topics:
    email-notifications:
      name: email-notifications
      partitions: 5
    sms-notifications:
      name: sms-notifications
      partitions: 5
    slack-notifications:
      name: slack-notifications
      partitions: 5