spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notifications
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/notifications
    user: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      acks: all
