server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest

#Custom
kafka:
  topics:
    email-notifications:
      name: email-notifications
      partitions: 5
    sms-notifications:
      name: sms-notifications
      partitions: 5
    slack-notifications:
      name: slack-notifications
      partitions: 5

org-metadata:
  base-url: ${ORG_METADATA_BASE_URL:http://localhost:8083}