server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest

#Custom
kafka:
  topics:
    email-notifications: email-notifications
    sms-notifications: sms-notifications
    slack-notifications: slack-notifications